name: Replicate S3 Folder to GitHub
on:
  schedule:
    - cron: '25 */4 * * *'
  workflow_dispatch:
jobs:
  replicate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Replicate S3 Folder
        run: |
          aws s3 sync s3://kin-sandbox-tmpdatalake-raw/noaa/ . --exclude "*" --include "*.geojson"
      - name: Run newest_data Python file
        run: |
          python newest_data_geojson.py
      - name: Commit and Push
        run: |
          git config --global user.email "sa_data-management@kin.com"
          git config --global user.name "kin-data-management"
          git add .
          git commit -m "Replicated S3 folder to GitHub"
          git push
